write_SASfmt <- function(data, format="txt", path=NULL, filename=NULL) {
  # warn if path is NULL
    if (is.null(path)) {warning("Must give a path to write to file")}
  # warn if filename is NULL
    if (is.null(filename)) {warning("Must give a filename to write to file")}
  # char of dataframe name
    df.name <- deparse(substitute(data))
  # get only continuous and character vars (is.numeric returns true for nums and ints)
    conts <- data[,sapply(data,is.numeric)]
    chars <- data[,sapply(data,is.character)]
    facs <- data[,sapply(data,is.factor)]
    chars.facs <- as.data.frame(cbind(chars, facs))
  # number of cont and char vars
    n.conts <- ncol(conts)
    n.chars.facs <- ncol(chars.facs)
  # change NA's to "." in continuous vars (not needed with write.forein?)
    # for (i in 1:n.conts) {
    #   # change to chars so we can change NA to "."
    #     conts[,i] <- as.character(conts[,i])
    #   # trim whitespace
    #     conts[,i] <- trim(conts[,i])  
    #   # change NA to "."
    #     conts[,i] <- ifelse(is.na(conts[,i]), ".", conts[,i]) 
    #     conts[,i] <- as.numeric(conts[,i])
    # }
  # change NA's to " " in character and factor vars
    for (i in 1:n.chars.facs) {
      # if factor change to char
        if (is.factor(chars.facs[,i])) {chars.facs[,i] <- as.character(chars.facs[,i])}
      # trim whitespace
        chars.facs[,i] <- trim(chars.facs[,i])
      # change NA to " "
        chars.facs[,i] <- ifelse(is.na(chars.facs[,i]), " ", chars.facs[,i])
    }
  # merge the cont and char/fac dataframes
    data2 <- as.data.frame(cbind(chars.facs, conts))   
  # create csv file
    if (format=="csv" & !is.null(path) & !is.null(filename))  {
      warning("As of 9/6/2016 SAS will not properly import these csv files\nrecommend using format='txt' instead")
      write.csv(data2, file=paste0(path, "/", filename, ".csv"), row.names=F)
      cat(paste0("csv file created at\n", paste0(path, "/", filename, ".csv")))
    }
  # create txt file with SAS code generated by write.foreign()  
    if (format=="txt" & !is.null(path) & !is.null(filename))  {
      library(foreign)
      write.foreign(data2, 
                     datafile=paste0(path, "/", filename, ".txt"),
                     codefile=paste0(path, "/", filename, ".sas"),
                     package="SAS")
      cat("txt dataset file created at\n",paste0(path, "/", filename, ".txt\n"))
      cat("Code for importing the new .txt dataset into SAS has been created at\n", paste0(path, "/", filename, ".sas"))
    }
    
}

save(write_SASfmt, file="C:/Users/Hunter/Desktop/Grad_School/Programming/R-SAS/Rstats/USER-FUNCTIONS/write_SASfmt.RData")
save(write_SASfmt, file="C:/Users/Hunter/Desktop/Grad_School/Research/Mehta/Analysis/crossroads/src/R-functions/write_SASfmt.RData")